### ISSUE TITLE
Ability to change table metadata

### ISSUE THREAD

**Issue by TRENDS-Charlie-Howe** [department-for-transport-public/dftutils#7]
**Describe the solution you'd like**

At the moment, there is no simple way to complete the final steps of creating accessible tables - though they can be converted to .ods, and a title can be added. The full process (once a table has been converted to .ods) currently looks something like this:

> Open table
> Copy document title so you don't lose it
> Inspect workbook (under File tab)
> Press 'Remove All' under Document Properties and Personal Information
> Add the title back in
> Add three or four tags based on the table content

This is not a large task, but multiplied by multiple tables for each release, and the many releases across DfT, it wastes a lot of time. My suggestion is therefore for a new function in dftutils (or an extension to convert_to_ods, which can do part of this task, but not all of it) which would automate these steps. 

**How this could be coded**

The function should ideally take a file, and optionally a title and/or tags. First it should remove any existing metadata that pose a security risk - these include e.g. absolute file paths, author names, etc. It would then add the document title and the tags, if provided.

@DIPAD-Fran-Bryden

**Comment by DIPAD-Fran-Bryden** [comment]
@TRENDS-Charlie-Howe A suggested fix for this is in the dev branch now. Do you want to have a go at installing and let me know if it does what you were expecting in the first instance, then I'll add testing and documentation before doing a new version of the package.
